= Give Love To Your JavaScript Adapters: the Making-Of
Xavier Vergés 
v0.1.0, 2015-3-16
:toc:
:toc-placement: preamble
:source-highlighter: pygments 	// coderay, highlightjs, prettify, and pygments.
:doctype: Article

What follows are the (decorated) notes I take while working on coding this project.

== Creating the MobileFirst Platform project from the CLI

----
>mfp create give-love-to-your-adapters
Error: Could not create MobileFirst Project.
Error: MobileFirst project names may only contain English alpha-numeric characters.
----

Oops. If I ever a write a http://yeoman.io/[Yeoman] generator do the 
boilerplate for MobileFirst Platform projects, I'll have to keep in mind
this restriction.

----
>mfp create GiveLoveToYourAdapters
A MobileFirst Project was successfully created at ...\GiveLoveToYourAdapters

>cd GiveLoveToYourAdapters
>git init
>git add .
>git commit -m "As created by mfp cli"
----

== Hi, new loveable adapter

----
>mfp add adapter loveableAdapter --type http
>git add .
>git commit -m "After mfp add adapter"
----

To the server, and beyond!

----
> mfp create-server
> mfp start
> mfp deploy
> mfp invoke loveableAdapter:getStories [\"world\"]
----

That last command is equivalent to just reaching the following URL 

----
http://localhost:10080/GiveLoveToYourAdapters/dev/invoke?adapter=loveableAdapter&procedure=getStories&parameters=["world"]
----

A `bin` directory appeared as a result of our deploy, and we needed to `.gitignore` it.

== Interlude: a backend to play with

Our loveable adapter will need a backend to interact with. I like 
http://couchdb.apache.org/[CouchDB] and I like https://cloudant.com/[Cloudant] 
(a BDaaS owned now by IBM, the company has been paying my bills for the last
20+ years). It looks like https://github.com/pouchdb/pouchdb-server[pouchdb-server] 
can make a nice and simple local CouchDB-compatible backend to play with;
or, easier to integrate with testing scripts, its main building block, 
https://github.com/pouchdb/express-pouchdb[express-pouchdb].

`a-sample-backend/server.js` creates a *PouchDB* in-memory server. It can be
executed standalone or from Grunt, with `grunt express express-keepalive`
thanks to https://github.com/blai/grunt-express[grunt-express].

== Static code analysis with JSHint

http://jshint.com[JSHint] _is a program that flags suspicious usage in programs 
written in JavaScript_. It can be http://jshint.com/install/[driven from the 
command line, from Grunt or often from your favorite editor]. You can tune
what it complains about using configuration files named `.jshintrc`, that 
affects the files in the folder and subfolders where it is placed. In the root
folder of the project, we will place a `.jshintrc` file in the project's root,
with all the options that we want to use for the JavaScript in our adapters,
our apps and our tests

[source, json]
----
include::.jshintrc[]
----

But we will also want to set some settings according to the environment where
our adapters are executed. We will do it in the file `adapters/.jshintrc`:

[source, json]
----
include::adapters/.jshintrc[]
----

To drive it with Grunt, we will need to install
https://github.com/gruntjs/grunt-contrib-jshint[grunt-contrib-jshint]

----
npm install grunt-contrib-jshint --save
----

On the `jshint` task, we  want to make sure that `.jshintrc` files are used and
that the `Gruntfile.js` itself is being checked:

[source, javascript]
----
jshint: {
  options: {
    jshintrc: true
  },
  gruntfile: {                      // An arbitary name for the subtask
    src: [patterns.js.gruntfile]    // patterns holds most file paths
  },
----

And now, `grunt jshint` checks our adapters and our gruntfile.

== A Lego approach to building adapters

HTML Adapters need to be implemented in a single JavaScript file. This makes
reusing and testing code very hard. Just like it is common when working in the
front-end to build a single, minified, JavaScript file from several other
files, we are going to build our adapter by assembling smaller files. Lets 
forget about code reuse by copy-and-paste. 

=== Pods

From https://github.com/gmac/pods.js: _Pods.js is a tiny synchronous module 
definition and dependency management library, built around a familiar 
define/require interface._ Our adapter file will be assembled with the 
`pods.js` file itself and the modules that we will define using it:

[source, javascript]
----
var modules = modules || new Pod();

modules.define('moduleA', function() {
    return {
        ...
    };
});
modules.define('moduleB', ['moduleA'], function(moduleA) {
    function factory() {
    ...
    }
    return factory; 
});
----

=== The directory structure for the Lego pieces

----
adapterlib/
  common/
    pods.js             <1>
    ...                 <2>
  loveableAdapter/
    ...                 <3>
    main.js             <4>
----

The files are numbered according to the order used to include them. 
`grunt concat` http://stackoverflow.com/q/17009874/239408[is
configured dynamically] to assemble an adapter for every subdir
in `adapterlib`.

